name: hackathon_vegas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  lottie: ^3.3.1
  nfc_manager: ^3.5.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bitlocker_icon.svg
    - assets/bitlocker_text.svg
